/**
 * Protocol Buffers implementation (proto3 binary wire + canonical JSON mapping).
 *
 * <p>The contract with chappe stays at the byte level: a {@code GrpcHandler}
 * calls {@code Parser.parseFrom(call.receive())} and
 * {@code call.send(message.toByteArray())}. No chappe API is implemented here.</p>
 *
 * <p>Edition 2023 features and codegen from {@code .proto} are handled in
 * {@code champollion-protobuf-codegen} and {@code champollion-protobuf-maven-plugin}.</p>
 */
module io.vidocq.champollion.protobuf {
    requires transitive io.vidocq.champollion.jsonp;

    exports io.vidocq.champollion.protobuf;
    exports io.vidocq.champollion.protobuf.wkt;

    // ServiceLoader SPI for the static parsers generated by the APT.
    uses io.vidocq.champollion.protobuf.ParserProvider;
}
