/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
/**
 * Protocol Buffers implementation (proto3 binary wire + canonical JSON mapping).
 *
 * <p>The contract with chappe stays at the byte level: a {@code GrpcHandler}
 * calls {@code Parser.parseFrom(call.receive())} and
 * {@code call.send(message.toByteArray())}. No chappe API is implemented here.</p>
 *
 * <p>Edition 2023 features and codegen from {@code .proto} are handled in
 * {@code champollion-protobuf-codegen} and {@code champollion-protobuf-maven-plugin}.</p>
 */
module io.vidocq.champollion.protobuf {
    requires transitive io.vidocq.champollion.jsonp;

    exports io.vidocq.champollion.protobuf;
    exports io.vidocq.champollion.protobuf.wkt;

    // ServiceLoader SPI for the static parsers generated by the APT.
    uses io.vidocq.champollion.protobuf.ParserProvider;
}
