<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <parent>
        <groupId>io.vidocq.champollion</groupId>
        <artifactId>champollion-parent</artifactId>
    </parent>

    <artifactId>champollion-examples</artifactId>
    <name>Champollion :: Examples</name>
    <description>Exemples d'utilisation JSON-P et JSON-B avec et sans codegen statique</description>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.vidocq.champollion</groupId>
            <artifactId>champollion-jsonp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.champollion</groupId>
            <artifactId>champollion-jsonb</artifactId>
        </dependency>
    </dependencies>
</project>
