package io.vidocq.champollion.protobuf.tck.proto3;

import io.vidocq.champollion.protobuf.ProtoEnumValue;

/**
 * {@code TestAllTypesProto3.NestedEnum} — proto3, NEG=-1 inclus.
 *
 * <p>Top-level to avoid the package/class collision generated by
 * the APT {@code ProtobufStaticProcessor} on nested types.</p>
 */
public enum NestedEnumT {
    FOO,                          // proto value = 0 (default)
    BAR,                          // proto value = 1
    BAZ,                          // proto value = 2
    @ProtoEnumValue(-1) NEG       // proto value = -1
}
