import io.vidocq.champollion.jsonb.spi.JsonbBinding;
import jakarta.json.bind.spi.JsonbProvider;

/**
 * Jakarta JSON Binding 3.0 implementation — reflective runtime (M4) with a
 * lookup-first path to the static bindings generated by
 * {@code champollion-codegen-apt} (M5), then a runtime fallback.
 */
module io.vidocq.champollion.jsonb {
    requires transitive io.vidocq.champollion.api;
    requires io.vidocq.champollion.jsonp;

    exports io.vidocq.champollion.jsonb.spi;

    uses JsonbBinding;

    provides JsonbProvider with io.vidocq.champollion.jsonb.internal.ChampollionJsonbProvider;
}
